[apt-update]
name = "apt-update"
command = "/usr/bin/apt-get update"
args = ["-y"]
description = "Updating package lists"

[apt-upgrade]
name = "apt-upgrade"
command = "/usr/bin/apt-get upgrade"
args = ["-y"]
description = "Upgrading packages"